modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "wyml"
version = "${version}"
displayName = "WhyYouMakeLag"
authors = "CreeperHost"
description = '''
Crab dance
'''
#logoFile = ""

[[dependencies.wyml]]
modId = "forge"
mandatory = true
versionRange = "[38,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wyml]]
modId = "minecraft"
mandatory = true
versionRange = "1.18"
ordering = "NONE"
side = "BOTH"
