plugins {
    id "com.gradleup.shadow"
    id "multiloader-loader"
    id "net.fabricmc.fabric-loom"
}

configurations {
    devRuntime
    runtimeClasspath.extendsFrom(devRuntime)
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_api_version}"
    implementation "net.creeperhost.polylib:polylib-fabric:${polylib_version}"
    compileOnly "dev.ftb.mods:ftb-chunks-fabric:${ftb_chunks_version}"
    devRuntime "dev.ftb.mods:ftb-chunks-fabric:${ftb_chunks_version}"

    implementation "blue.endless:jankson:1.2.1"
    shadow("blue.endless:jankson:1.2.1") { transitive = false }
}

loom {
    accessWidenerPath = project(":common").file("src/main/resources/wyml.accesswidener")
    runs {
        client {
            client()
            ideConfigGenerated(true)
            runDir("runs/client")
        }
        server {
            server()
            ideConfigGenerated(true)
            runDir("runs/server")
        }
    }
}

jar {
    archiveClassifier = "dev"
}

shadowJar {
    dependsOn(jar)
    configurations = [project.configurations.shadow]
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    relocate "blue.endless.jankson", "net.creeperhost.wyml.blue.endless.jankson"
    archiveClassifier = null
}

configurations {
    [apiElements, runtimeElements].each { config ->
        config.outgoing.artifacts.clear()
        config.outgoing.artifact(shadowJar)
    }
}

assemble.dependsOn(shadowJar)

publishing {
    publications.named("mavenJava", MavenPublication) {
        artifactId = "${archives_base_name}-fabric"
    }
}
