plugins {
    id "multiloader-common"
    id "net.neoforged.moddev"
}

neoForge {
    neoFormVersion = neo_form_version
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.5"
    compileOnly "org.ow2.asm:asm-tree:${asm_version}"
    compileOnly "net.creeperhost.polylib:polylib-neoforge:${polylib_version}"
    accessTransformers "net.creeperhost.polylib:polylib-neoforge:${polylib_version}"
    compileOnly "dev.ftb.mods:ftb-chunks-neoforge:${ftb_chunks_version}"
    implementation "blue.endless:jankson:1.2.1"
    testImplementation "org.junit.jupiter:junit-jupiter:5.11.4"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher:1.11.4"
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

def loaderAttribute = Attribute.of("io.github.mcgradleconventions.loader", String)
["apiElements", "runtimeElements", "sourcesElements"].each { variant ->
    configurations.named(variant) {
        attributes {
            attribute(loaderAttribute, "common")
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant ->
        configurations.named(variant) {
            attributes {
                attribute(loaderAttribute, "common")
            }
        }
    }
}
