plugins {
    id "com.gradleup.shadow"
    id "multiloader-loader"
    id "net.neoforged.moddev"
}

neoForge {
    version = neoforge_version
    runs {
        configureEach {
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = file("runs/client")
        }
        server {
            server()
            gameDirectory = file("runs/server")
        }
    }
    mods {
        wyml {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation "net.creeperhost.polylib:polylib-neoforge:${polylib_version}"
    accessTransformers "net.creeperhost.polylib:polylib-neoforge:${polylib_version}"

    implementation "blue.endless:jankson:1.2.1"
    shadow("blue.endless:jankson:1.2.1") { transitive = false }
}

jar {
    archiveClassifier = "dev"
}

shadowJar {
    dependsOn(jar)
    configurations = [project.configurations.shadow]
    mainSpec.sourcePaths.clear()
    from(zipTree(jar.archiveFile))
    relocate "blue.endless.jankson", "net.creeperhost.wyml.blue.endless.jankson"
    archiveClassifier = null
}

configurations {
    [apiElements, runtimeElements].each { config ->
        config.outgoing.artifacts.clear()
        config.outgoing.artifact(shadowJar)
    }
}

assemble.dependsOn(shadowJar)

publishing {
    publications.named("mavenJava", MavenPublication) {
        artifactId = "${archives_base_name}-neoforge"
    }
}
